[workspace]
resolver = "2"

members = [
    "emulator",
    "emulator/ssd1306-emulator",
    "emulator/nt3h-emulator",
    "gui",
    "model",
    "dummy-uniffi",
    "fetch-git-hash",
    "sdk",
    "functional-test-wrapper",
]
exclude = [
    # Sigh
    "firmware",
]
